name: unipd_mobile
description: Tirocinio SFP Unipd

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.0+13

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # Core packages
  intl: ^0.17.0
  get: ^4.6.5
  get_cli: ^1.7.1
  dio: ^4.0.6
  flutter_secure_storage: ^5.0.2
  device_info_plus: ^3.2.0
  responsive_builder: ^0.4.2
  equatable: ^2.0.3
  webview_flutter: ^3.0.2
  flutter_webview_plugin: ^0.4.0
  jwt_decoder: ^2.0.1
  url_launcher: ^6.1.2
  package_info_plus: ^1.4.2


  # Utility
  email_validator: ^2.0.1
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.0.9
  flutter_native_splash: ^2.0.5
  clipboard: ^0.1.3
  mock_data: ^2.0.0
  misslog:
    git: https://github.com/Mapk26/misslog.git 

  

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter_icons:

  android: "launcher_icon"

  ios: true

  image_path: "assets/images/logo-univers-padova.jpg"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Regular.ttf
        - asset: assets/fonts/Lato/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/Lato/Lato-Italic.ttf
          style: italic
  
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald/Oswald-Regular.ttf

    - family: OpenSans
      fonts:
        - asset: assets/fonts/Open_Sans/OpenSans-Regular.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/Open_Sans/OpenSans-Italic.ttf
          style: italic